---
- name: Create the user that will run the server
  become: true
  ansible.builtin.user:
    state: present
    name: "{{ steam_username }}"
    password: "!"
    create_home: true
    shell: /bin/bash

- name: Add current user to the steamuser group
  become: true
  ansible.builtin.user:
    state: present
    name: "{{ ansible_user_id }}"
    groups: "{{ steam_username }}"
    append: true

- name: Create the working directory for SteamCmd
  become: true
  become_user: "{{ steam_username }}"
  ansible.builtin.file:
    path: "{{ steamcmd_dir }}"
    state: directory
    mode: '0750'




...
